# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Repository information for GitHub Pages
repository: g7xu/g7xu.github.io
url: "https://g7xu.github.io"
baseurl: ""

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Jason (Guoxuan) Xu"
email: g7xu@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  An Undergraduate student at University of California San Diego
github_username: g7xu
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.26.2
sass:
  sass_dir: _sass
  style: compressed
github: [metadata]

# Performance optimizations
incremental: true
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false

# SEO improvements
seo:
  title: "Guoxuan Xu - Data Science Student & Researcher"
  description: "Personal website of Guoxuan Xu, Data Science student at UC San Diego. Projects, research, and learning resources."
  author: "Guoxuan Xu"
  image: "/assets/images/bio-photo.jpg"
  url: "https://g7xu.github.io"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

author:
  name   : "Guoxuan Xu"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Hi, I am Guoxuan (pronounced as Gwo-shwan), or you can go by Jason."
  location: "San Diego, CA"
  email: g7xu@ucsd.edu
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/g7xu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guoxuan-xu-30a572269/"
    - label: "Resume"
      icon: "fas fa-fw fa-file"
      url: "../assets/files/Guoxuan_Data_Science_resume.pdf"
    - label: "CV"
      icon: "fas fa-fw fa-file"
      url: "assets/cv.pdf"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/g7xu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guoxuan-xu-30a572269/"
    - label: "Resume"
      icon: "fas fa-fw fa-file"
      url: "https://drive.google.com/file/d/1-oVa5gqUFUzMBka8b9seSEbbPpVPAvSE/view?usp=sharing"
    - label: "CV"
      icon: "fas fa-fw fa-file"
      url: "assets/cv.pdf"

# allow people to leave comments on the website
# TODO: still need to fix
comments:
  provider: disqus
  disqus:
    shortname: "guoxuan"

main:
  - title: "Learning Wiki"
    url: /learning-wiki/
  - title: "Beyond-Tech"
    url: /Beyond-Tech/
  - title: "Categories"
    url: /categories/


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false 
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      include: ["scripts", "structured-data"]

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
